version: 2

formats: []

sphinx:
  builder: html
  configuration: docs/conf.py

build:
    image: latest

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
  system_packages: true
