branches:
  only:
    - "master"

services:
  - docker

language: python

cache: pip

env:
  global:

matrix:
  include:
    - stage: Lint and Code Style
      python: 3.7
      env: TOXENV=lint

    - stage: Tests and Coverage
      python: 3.7
      env: TOXENV=py37
    - if: type = push
      python: 3.8
      env: TOXENV=py38
    - if: type = push
      python: 3.9
      env: TOXENV=py39

    - stage: Docs
      python: 3.7
      env: TOXENV=docs

    - stage: Packaging
      if: type = push
      python: 3.7
      env: TOXENV=check-packaging

before_install:
  # make sure latest docker installed
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - pip install tox

script:
  - tox -vv
