branches:
  only:
    - "master"

services:
  - docker

language: python

cache:
    directories:
        - $HOME/.cache/pip

env:
  global:
    - VIRTUALENV_PIP="20.2.4"

matrix:
  include:
    - stage: Lint and Code Style
      python: 3.8
      env: TOXENV=lint

    - stage: Tests and Coverage
      python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

    - stage: Docs
      python: 3.8
      env: TOXENV=docs

    - stage: Packaging
      python: 3.8
      env: TOXENV=check-packaging

before_install:
  # make sure latest docker installed
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - pip install tox

script:
  - tox -vv
