language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install --upgrade .[dev]
# command to run tests
script: pytest