branches:
  only:
    - "master"

services:
  - docker

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
  include:
    - stage: Lint and Code Style
      python: 3.8
      env: TOXENV=lint

    - stage: Docs
      python: 3.8
      env: TOXENV=docs

    - stage: Packaging
      python: 3.8
      env: TOXENV=check-packaging

    - stage: Tests and Coverage
      python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install:
  - pip install tox

script:
  - tox
