version: "3"
services:
  search:
    build:
      context: .
      dockerfile: docker/Dockerfile-search_server
    image: bbs_search
    ports:
      - "8850:8080"
    volumes:
      - /raid:/raid
  mining:
    build:
      context: .
      dockerfile: docker/Dockerfile-mining_server
    image: bbs_mining
    ports:
      - "8852:8080"
    volumes:
      - /raid:/raid
