version: "3.5"
services:
  test:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    image: bbs_test
    container_name: bbs_test_container

  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - http_proxy
        - https_proxy
    image: bbs_base
    container_name: bbs_base
    networks:
      - bbs_network

  search:
    build:
      context: .
      dockerfile: docker/search.Dockerfile
    image: bbs_search
    container_name: bbs_search
    ports:
      - 8850:8080
    volumes:
      - /raid:/raid
    networks:
      - bbs_network

  embedding:
    build:
      context: .
      dockerfile: docker/embedding.Dockerfile
    image: bbs_embedding
    container_name: bbs_embedding
    ports:
      - 8851:8080
    volumes:
      - /raid:/raid
    networks:
      - bbs_network

  mining:
    build:
      context: .
      dockerfile: docker/mining.Dockerfile
    image: bbs_mining
    container_name: bbs_mining
    ports:
      - 8852:8080
    volumes:
      - /raid:/raid
    networks:
      - bbs_network

networks:
  bbs_network:
    driver: bridge
