stages:
  convert_annotations:
    # FIXME Move stages converting annotations to one model per entity.
    foreach:
      - annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease
      - annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi
      - annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein
      - annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes
      - annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes
      - annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes
      - annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes
      - annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan
      - annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway
    do:
      cmd: python preprocess.py ../../annotations/ner/${item}.jsonl
      deps:
        - Dockerfile
        - preprocess.py
        - ../../annotations/ner/${item}.jsonl
      params:
        - train.corpora.dev_size
        - train.corpora.shuffle_seed
      outs:
        - ../../annotations/ner/${item}.train.spacy
        - ../../annotations/ner/${item}.dev.spacy
  training:
    foreach:
      model-cell_compartment: annotations14_cell_compartment
      model-cell_type: annotations9_cell_type
      model-chemical: annotations6_chemical
      model-disease: annotations5_disease
      model-drug: annotations14_drug
      model-organ: annotations14_organ
      model-organism: annotations6_organism
      model-pathway: annotations15_pathway
      model-protein: annotations9_protein
    do:
      cmd: >-
        python -m spacy train
        config.cfg
        --output ../../models/ner/${key}/
        --gpu-id 0
        --paths.train ../../annotations/ner/${item}.train.spacy
        --paths.dev ../../annotations/ner/${item}.dev.spacy
        &&
        python patch.py ../../models/ner/${key}/model-best/vocab/strings.json
      deps:
      - Dockerfile
      - config.cfg
      - ../../annotations/ner/${item}.train.spacy
      - ../../annotations/ner/${item}.dev.spacy
      outs:
      - ../../models/ner/${key}/model-best/
  add_er:
    foreach:
      - cell_compartment
      - cell_type
      - chemical
      - disease
      - drug
      - organ
      - organism
      - pathway
      - protein
     do:
        cmd: python add_er.py --model ../../models/ner/model-${item}/model-best/ --etypes ${item} --patterns_file ../../annotations/ner/rule_based_patterns.jsonl --output_file ../../models/ner_er/model-${item}
        deps:
        - Dockerfile
        - ../../models/ner/model-${item}/model-best/
        - add_er.py
        - ../../annotations/ner/rule_based_patterns.jsonl
        params:
        - eval.${item}
        outs:
        - ../../models/ner_er/model-${item}
  evaluation:
    foreach:
      - cell_compartment
      - cell_type
      - chemical
      - disease
      - drug
      - organ
      - organism
      - pathway
      - protein
    do:
      cmd: python eval.py
      --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model-${item} --output_file ../../metrics/ner/${item}.json --etype ${item}
      deps:
      - Dockerfile
      - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
      - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      - ../../models/ner_er/model-${item}
      - eval.py
      params:
      - eval.${item}
      metrics:
      - ../../metrics/ner/${item}.json:
          cache: false
  interrater:
    cmd: python interrater.py --annotations1 ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl        --annotations2 ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl,../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
      --output_dir ../../metrics/ner/interrater/
    deps:
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    - Dockerfile
    - interrater.py
    metrics:
    - ../../metrics/ner/interrater/cell_compartment.json:
        cache: false
    - ../../metrics/ner/interrater/cell_type.json:
        cache: false
    - ../../metrics/ner/interrater/chemical.json:
        cache: false
    - ../../metrics/ner/interrater/condition.json:
        cache: false
    - ../../metrics/ner/interrater/disease.json:
        cache: false
    - ../../metrics/ner/interrater/drug.json:
        cache: false
    - ../../metrics/ner/interrater/organ.json:
        cache: false
    - ../../metrics/ner/interrater/organism.json:
        cache: false
    - ../../metrics/ner/interrater/pathway.json:
        cache: false
    - ../../metrics/ner/interrater/protein.json:
        cache: false
