stages:
  # TODO Remove boilerplate for convert_annotations_* with DVC 2 foreach.
  # https://github.com/BlueBrain/Search/issues/308 would remove the need of
  # converting the annotations by dropping the .jsonl format for the .spacy one.
  convert_annotations_5:
    cmd: python preprocess.py ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.train.spacy
    - ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.dev.spacy
  convert_annotations_6:
    cmd: python preprocess.py ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.train.spacy
    - ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.dev.spacy
  convert_annotations_9:
    cmd: python preprocess.py ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.train.spacy
    - ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.dev.spacy
  convert_annotations_10:
    cmd: python preprocess.py ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.train.spacy
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.dev.spacy
  convert_annotations_11:
    cmd: python preprocess.py ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.train.spacy
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.dev.spacy
  convert_annotations_12:
    cmd: python preprocess.py ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.train.spacy
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.dev.spacy
  convert_annotations_13:
    cmd: python preprocess.py ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.train.spacy
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.dev.spacy
  convert_annotations_14:
    cmd: python preprocess.py ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.train.spacy
    - ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.dev.spacy
  convert_annotations_15:
    cmd: python preprocess.py ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.jsonl
    deps:
    - Dockerfile
    - preprocess.py
    - ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.jsonl
    params:
    - train.eval_split
    outs:
    - ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.train.spacy
    - ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.dev.spacy
  # TODO Remove boilerplate for train_model_* with DVC 2 foreach.
  train_model_1:
    cmd: >-
      python -m spacy train
      config.cfg
      --output ../../models/ner/model1/
      --code initialize.py
      --paths.train ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.train.spacy
      --paths.dev ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.dev.spacy
      --paths.base_model en_ner_bc5cdr_md
    deps:
    - Dockerfile
    - config.cfg
    - initialize.py
    - ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.train.spacy
    - ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.dev.spacy
    outs:
    - ../../models/ner/model1/model-best/
  train_model_2:
    cmd: >-
      python -m spacy train
      config.cfg
      --output ../../models/ner/model2/
      --code initialize.py
      --paths.train ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.train.spacy
      --paths.dev ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.dev.spacy
      --paths.base_model en_ner_bionlp13cg_md
    deps:
    - Dockerfile
    - config.cfg
    - initialize.py
    - ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.train.spacy
    - ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.dev.spacy
    outs:
    - ../../models/ner/model2/model-best/
  train_model_3:
    cmd: >-
      python -m spacy train
      config.cfg
      --output ../../models/ner/model3/
      --code initialize.py
      --paths.train ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.train.spacy
      --paths.dev ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.dev.spacy
      --paths.base_model en_ner_craft_md
    deps:
    - Dockerfile
    - config.cfg
    - initialize.py
    - ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.train.spacy
    - ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.dev.spacy
    outs:
    - ../../models/ner/model3/model-best/
  train_model_4:
    cmd: >-
      python -m spacy train
      config.cfg
      --output ../../models/ner/model4/
      --code initialize.py
      --paths.train ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.train.spacy
      --paths.dev ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.dev.spacy
      --paths.base_model en_ner_jnlpba_md
    deps:
    - Dockerfile
    - config.cfg
    - initialize.py
    - ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.train.spacy
    - ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.dev.spacy
    outs:
    - ../../models/ner/model4/model-best/
  train_model_5:
    cmd: >-
      python -m spacy train
      config.cfg
      --output ../../models/ner/model5/
      --code initialize.py
      --paths.train ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.train.spacy
      --paths.dev ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.dev.spacy
      --paths.base_model en_ner_craft_md
    deps:
    - Dockerfile
    - config.cfg
    - initialize.py
    - ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.train.spacy
    - ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.dev.spacy
    outs:
    - ../../models/ner/model5/model-best/
  add_er_1:
    cmd: python add_er.py --model ../../models/ner/model1/model-best/ --etypes DISEASE --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model1
    deps:
    - Dockerfile
    - ../../models/ner/model1/model-best/
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.DISEASE
    outs:
    - ../../models/ner_er/model1
  add_er_2:
    cmd: python add_er.py --model ../../models/ner/model2/model-best/ --etypes CELL_COMPARTMENT,DRUG,ORGAN --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model2
    deps:
    - Dockerfile
    - ../../models/ner/model2/model-best/
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.CELL_COMPARTMENT
    - eval.DRUG
    - eval.ORGAN
    outs:
    - ../../models/ner_er/model2
  add_er_3:
    cmd: python add_er.py --model ../../models/ner/model3/model-best/ --etypes CHEMICAL,ORGANISM --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model3
    deps:
    - Dockerfile
    - ../../models/ner/model3/model-best/
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.CHEMICAL
    - eval.ORGANISM
    outs:
    - ../../models/ner_er/model3
  add_er_4:
    cmd: python add_er.py --model ../../models/ner/model4/model-best/ --etypes CELL_TYPE,PROTEIN --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model4
    deps:
    - Dockerfile
    - ../../models/ner/model4/model-best/
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.CELL_TYPE
    - eval.PROTEIN
    outs:
    - ../../models/ner_er/model4
  add_er_5:
    cmd: python add_er.py --model ../../models/ner/model5/model-best/ --etypes PATHWAY --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model5
    deps:
    - Dockerfile
    - ../../models/ner/model5/model-best/
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.PATHWAY
    outs:
    - ../../models/ner_er/model5
  eval_disease:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model1 --output_file ../../metrics/ner/disease.json
      --etype DISEASE
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model1
    - eval.py
    params:
    - eval.DISEASE
    metrics:
    - ../../metrics/ner/disease.json
  eval_cell_compartment:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model2 --output_file ../../metrics/ner/cell_compartment.json
      --etype CELL_COMPARTMENT
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model2
    - eval.py
    params:
    - eval.CELL_COMPARTMENT
    metrics:
    - ../../metrics/ner/cell_compartment.json
  eval_drug:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model2 --output_file ../../metrics/ner/drug.json --etype
      DRUG
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model2
    - eval.py
    params:
    - eval.DRUG
    metrics:
    - ../../metrics/ner/drug.json
  eval_organ:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model2 --output_file ../../metrics/ner/organ.json --etype
      ORGAN
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model2
    - eval.py
    params:
    - eval.ORGAN
    metrics:
    - ../../metrics/ner/organ.json
  eval_chemical:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model3 --output_file ../../metrics/ner/chemical.json
      --etype CHEMICAL
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model3
    - eval.py
    params:
    - eval.CHEMICAL
    metrics:
    - ../../metrics/ner/chemical.json
  eval_organism:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model3 --output_file ../../metrics/ner/organism.json
      --etype ORGANISM
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model3
    - eval.py
    params:
    - eval.ORGANISM
    metrics:
    - ../../metrics/ner/organism.json
  eval_cell_type:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model4 --output_file ../../metrics/ner/cell_type.json
      --etype CELL_TYPE
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model4
    - eval.py
    params:
    - eval.CELL_TYPE
    metrics:
    - ../../metrics/ner/cell_type.json
  eval_protein:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model4 --output_file ../../metrics/ner/protein.json
      --etype PROTEIN
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model4
    - eval.py
    params:
    - eval.PROTEIN
    metrics:
    - ../../metrics/ner/protein.json
  eval_pathway:
    cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --model ../../models/ner_er/model5 --output_file ../../metrics/ner/pathway.json
      --etype PATHWAY
    deps:
    - Dockerfile
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../models/ner_er/model5
    - eval.py
    params:
    - eval.PATHWAY
    metrics:
    - ../../metrics/ner/pathway.json
  interrater:
    cmd: python interrater.py --annotations1 ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      --annotations2 ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl,../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
      --output_dir ../../metrics/ner/interrater/
    deps:
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    - Dockerfile
    - interrater.py
    metrics:
    - ../../metrics/ner/interrater/cell_compartment.json
    - ../../metrics/ner/interrater/cell_type.json
    - ../../metrics/ner/interrater/chemical.json
    - ../../metrics/ner/interrater/condition.json
    - ../../metrics/ner/interrater/disease.json
    - ../../metrics/ner/interrater/drug.json
    - ../../metrics/ner/interrater/organ.json
    - ../../metrics/ner/interrater/organism.json
    - ../../metrics/ner/interrater/pathway.json
    - ../../metrics/ner/interrater/protein.json
