stages:
  clean:
    foreach:
      cell_compartment:
        file: annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan
        label: cellular_component
      cell_type:
        file: annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein
        label: cell_type
      chemical:
        file: annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi
        label: chebi
      disease:
        file: annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease
        label: disease
      drug:
        file: annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan
        label: simple_chemical
      organ:
        file: annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan
        label: organ
      organism:
        file: annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi
        label: taxon
      pathway:
        file: annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway
        label: pathway
      protein:
        file: annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein
        label: protein
    do:
      cmd: python clean.py ../../annotations/ner/${item.file}.jsonl ${item.label} --renamed-label ${key}
      deps:
      - Dockerfile
      - clean.py
      - ../../annotations/ner/${item.file}.jsonl
      outs:
      - ../../annotations/ner/annotations_${key}.jsonl
  preprocess:
    foreach: ${entities}
    do:
      cmd: python preprocess.py ../../annotations/ner/annotations_${item}.jsonl
      deps:
      - Dockerfile
      - preprocess.py
      - ../../annotations/ner/annotations_${item}.jsonl
      params:
      - train.corpora.dev_size
      - train.corpora.shuffle_seed
      outs:
      - ../../annotations/ner/annotations_${item}.train.spacy
      - ../../annotations/ner/annotations_${item}.dev.spacy
  train:
    foreach: ${entities}
    do:
      cmd: >-
        python -m spacy train
        config.cfg
        --output ../../models/ner/model-${item}/
        --paths.train ../../annotations/ner/annotations_${item}.train.spacy
        --paths.dev ../../annotations/ner/annotations_${item}.dev.spacy
      deps:
      - Dockerfile
      - config.cfg
      - ../../annotations/ner/annotations_${item}.train.spacy
      - ../../annotations/ner/annotations_${item}.dev.spacy
      - ../../models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/
      outs:
      - ../../models/ner/model-${item}/model-best/
  add_er:
    foreach: ${entities}
    do:
      # Regarding the use of 'sed':
      # See for details https://github.com/BlueBrain/Search/pull/395.
      # Will be removed by https://github.com/BlueBrain/Search/issues/310.
      cmd: >-
        python add_er.py
        --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
        --model ../../models/ner/model-${item}/model-best/
        --output_file ../../models/ner_er/model-${item}
        &&
        sed -i "s|$(pwd)/||g" ../../models/ner_er/model-${item}/transformer/model/*.json
      deps:
      - Dockerfile
      - add_er.py
      - ../../annotations/ner/rule_based_patterns.jsonl
      - ../../models/ner/model-${item}/model-best/
      params:
      - eval.${item}
      outs:
      - ../../models/ner_er/model-${item}
  evaluate:
    foreach: ${entities}
    do:
      cmd: >-
        python eval.py
        --etype ${item}
        --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
        --model ../../models/ner_er/model-${item}
        --output_file ../../metrics/ner/${item}.json
      deps:
      - Dockerfile
      - eval.py
      - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
      - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      - ../../models/ner_er/model-${item}
      params:
      - eval.${item}
      metrics:
      - ../../metrics/ner/${item}.json:
          cache: false
  interrater:
    cmd: python interrater.py --annotations1 ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl        --annotations2 ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl,../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
      --output_dir ../../metrics/ner/interrater/
    deps:
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    - Dockerfile
    - interrater.py
    metrics:
    - ../../metrics/ner/interrater/cell_compartment.json:
        cache: false
    - ../../metrics/ner/interrater/cell_type.json:
        cache: false
    - ../../metrics/ner/interrater/chemical.json:
        cache: false
    - ../../metrics/ner/interrater/condition.json:
        cache: false
    - ../../metrics/ner/interrater/disease.json:
        cache: false
    - ../../metrics/ner/interrater/drug.json:
        cache: false
    - ../../metrics/ner/interrater/organ.json:
        cache: false
    - ../../metrics/ner/interrater/organism.json:
        cache: false
    - ../../metrics/ner/interrater/pathway.json:
        cache: false
    - ../../metrics/ner/interrater/protein.json:
        cache: false
