stages:
  convert_annotations:
    foreach:
      - annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease
      - annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi
      - annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein
      - annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes
      - annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes
      - annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes
      - annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes
      - annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan
      - annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway
    do:
      cmd: python preprocess.py ../../annotations/ner/${item}.jsonl
      deps:
        - Dockerfile
        - preprocess.py
        - ../../annotations/ner/${item}.jsonl
      params:
        - train.corpora.dev_size
        - train.corpora.shuffle_seed
      outs:
        - ../../annotations/ner/${item}.train.spacy
        - ../../annotations/ner/${item}.dev.spacy
  training:
    foreach:
       model1:
         annotation_filename: annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease
         base_model: en_ner_bc5cdr_md
       model2:
         annotation_filename: annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan
         base_model: en_ner_bionlp13cg_md
       model3:
         annotation_filename: annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi
         base_model: en_ner_craft_md
       model4:
         annotation_filename: annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein
         base_model: en_ner_jnlpba_md
       model5:
         annotation_filename: annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway
         base_model: en_ner_craft_md
    do:
      cmd: >-
        python -m spacy train
        config.cfg
        --output ../../models/ner/${key}/
        --paths.train ../../annotations/ner/${item.annotation_filename}.train.spacy
        --paths.dev ../../annotations/ner/${item.annotation_filename}.dev.spacy
        --paths.base_model ${item.base_model}
      deps:
      - Dockerfile
      - config.cfg
      - ../../annotations/ner/${item.annotation_filename}.train.spacy
      - ../../annotations/ner/${item.annotation_filename}.dev.spacy
      outs:
      - ../../models/ner/${key}/model-best/
  add_er:
    foreach:
      - cell_compartment
      - cell_type
      - chemical
      - disease
      - drug
      - organ
      - organism
      - pathway
      - protein
    do:
      cmd: python add_er.py --model ../../models/ner/model-${item}/model-best/ --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
        --output_file ../../models/ner_er/model-${item}
      deps:
      - Dockerfile
      - ../../models/ner/model-${item}/model-best/
      - add_er.py
      - ../../annotations/ner/rule_based_patterns.jsonl
      outs:
      - ../../models/ner_er/model-${item}
  evaluation:
    foreach:
      disease:
        model_name: model1
      cell_compartment:
        model_name: model2
      drug:
        model_name: model2
      organ:
        model_name: model2
      chemical:
        model_name: model3
      organism:
        model_name: model3
      cell_type:
        model_name: model4
      protein:
        model_name: model4
      pathway:
        model_name: model5
    do:
      cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl --model ../../models/ner_er/${item.model_name} --output_file ../../metrics/ner/${key}.json --etype ${key}
      deps:
      - Dockerfile
      - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
      - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      - ../../models/ner_er/${item.model_name}
      - eval.py
      params:
      - eval.${key}
      metrics:
      - ../../metrics/ner/${key}.json:
          cache: false
  interrater:
    cmd: python interrater.py --annotations1 ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl        --annotations2 ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl,../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
      --output_dir ../../metrics/ner/interrater/
    deps:
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    - Dockerfile
    - interrater.py
    metrics:
    - ../../metrics/ner/interrater/cell_compartment.json:
        cache: false
    - ../../metrics/ner/interrater/cell_type.json:
        cache: false
    - ../../metrics/ner/interrater/chemical.json:
        cache: false
    - ../../metrics/ner/interrater/condition.json:
        cache: false
    - ../../metrics/ner/interrater/disease.json:
        cache: false
    - ../../metrics/ner/interrater/drug.json:
        cache: false
    - ../../metrics/ner/interrater/organ.json:
        cache: false
    - ../../metrics/ner/interrater/organism.json:
        cache: false
    - ../../metrics/ner/interrater/pathway.json:
        cache: false
    - ../../metrics/ner/interrater/protein.json:
        cache: false

