stages:
  train_models:
    foreach:
       - annotation_files: ../../annotations/ner/annotations5_EmmanuelleLogette_2020-06-30_raw2_Disease.jsonl
         model_name: model1
       - annotation_files: ../../annotations/ner/annotations14_EmmanuelleLogette_2020-09-02_raw8_CellCompartmentDrugOrgan.jsonl
         model_name: model2
       - annotation_files: ../../annotations/ner/annotations6_EmmanuelleLogette_2020-07-07_raw4_TaxonChebi.jsonl
         model_name: model3
       - annotation_files: ../../annotations/ner/annotations9_EmmanuelleLogette_2020-07-08_raw6_CelltypeProtein.jsonl
         model_name: model4
       - annotation_files: ../../annotations/ner/annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.jsonl
         model_name: model5
    do:
        cmd: python train.py --annotation_files ${item.annotation_files}
             --output_dir ../../models/ner/${item.model_name} --model_name ${item.model_name}
        deps:
                - ${item.annotation_files}
                - train.py
                - Dockerfile
        params:
                - train.${item.model_name}
        outs:
                - ../../models/ner/${item.model_name}
  add_er_1:
    cmd: python add_er.py --model ../../models/ner/model1 --etypes DISEASE --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model1
    deps:
    - Dockerfile
    - ../../models/ner/model1
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.DISEASE
    outs:
    - ../../models/ner_er/model1
  add_er_2:
    cmd: python add_er.py --model ../../models/ner/model2 --etypes CELL_COMPARTMENT,DRUG,ORGAN --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model2
    deps:
    - Dockerfile
    - ../../models/ner/model2
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.CELL_COMPARTMENT
    - eval.DRUG
    - eval.ORGAN
    outs:
    - ../../models/ner_er/model2
  add_er_3:
    cmd: python add_er.py --model ../../models/ner/model3 --etypes CHEMICAL,ORGANISM --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model3
    deps:
    - Dockerfile
    - ../../models/ner/model3
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.CHEMICAL
    - eval.ORGANISM
    outs:
    - ../../models/ner_er/model3
  add_er_4:
    cmd: python add_er.py --model ../../models/ner/model4 --etypes CELL_TYPE,PROTEIN --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model4
    deps:
    - Dockerfile
    - ../../models/ner/model4
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.CELL_TYPE
    - eval.PROTEIN
    outs:
    - ../../models/ner_er/model4
  add_er_5:
    cmd: python add_er.py --model ../../models/ner/model5 --etypes PATHWAY --patterns_file ../../annotations/ner/rule_based_patterns.jsonl
      --output_file ../../models/ner_er/model5
    deps:
    - Dockerfile
    - ../../models/ner/model5
    - add_er.py
    - ../../annotations/ner/rule_based_patterns.jsonl
    params:
    - eval.PATHWAY
    outs:
    - ../../models/ner_er/model5
  evals:
    foreach:
       - model_name: model1
         etype: DISEASE
       - model_name: model2
         etype: CELL_COMPARTMENT
       - model_name: model2
         etype: DRUG
       - model_name: model2
         etype: ORGAN
       - model_name: model3
         etype: CHEMICAL
       - model_name: model3
         etype: ORGANISM
       - model_name: model4
         etype: CELL_TYPE
       - model_name: model4
         etype: PROTEIN
       - model_name: model5
         etype: PATHWAY
    do:
      cmd: python eval.py --annotation_files ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl --model ../../models/ner_er/${item.model_name} --output_file ../../metrics/ner/${item.etype}.json --etype ${item.etype}
      deps:
      - Dockerfile
      - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
      - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
      - ../../models/ner_er/${item.model_name}
      - eval.py
      params:
      - eval.${item.etype}
      metrics:
      - ../../metrics/ner/${item.etype}.json
  interrater:
    cmd: python interrater.py --annotations1 ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl,../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl        --annotations2 ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl,../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
      --output_dir ../../metrics/ner/interrater/
    deps:
    - ../../annotations/ner/annotations10_EmmanuelleLogette_2020-08-28_raw1_raw5_10EntityTypes.jsonl
    - ../../annotations/ner/annotations11_CharlotteLorin_2020-08-28_raw1_10EntityTypes.jsonl
    - ../../annotations/ner/annotations12_EmmanuelleLogette_2020-08-28_raw7_10EntityTypes.jsonl
    - ../../annotations/ner/annotations13_CharlotteLorin_2020-09-02_raw7_10EntityTypes.jsonl
    - Dockerfile
    - interrater.py
    metrics:
    - ../../metrics/ner/interrater/cell_compartment.json
    - ../../metrics/ner/interrater/cell_type.json
    - ../../metrics/ner/interrater/chemical.json
    - ../../metrics/ner/interrater/condition.json
    - ../../metrics/ner/interrater/disease.json
    - ../../metrics/ner/interrater/drug.json
    - ../../metrics/ner/interrater/organ.json
    - ../../metrics/ner/interrater/organism.json
    - ../../metrics/ner/interrater/pathway.json
    - ../../metrics/ner/interrater/protein.json
