train:
  model1:
    prodigy_train_kwargs:
      spacy_model: en_ner_bc5cdr_md
      eval_split: 0.1
      n_iter: 10
      dropout: 0.2
  model2:
    prodigy_train_kwargs:
      spacy_model: en_ner_bionlp13cg_md
      eval_split: 0.1
      n_iter: 10
      dropout: 0.2
  model3:
    prodigy_train_kwargs:
      spacy_model: en_ner_craft_md
      eval_split: 0.1
      n_iter: 10
      dropout: 0.2
  model4:
    prodigy_train_kwargs:
      spacy_model: en_ner_jnlpba_md
      eval_split: 0.1
      n_iter: 10
      dropout: 0.2
  model5:
    prodigy_train_kwargs:
      spacy_model: en_ner_craft_md
      eval_split: 0.1
      n_iter: 10
      dropout: 0.2
eval:
  model1:
    etypes:
      DISEASE: DISEASE
  model2:
    etypes:
      CELL_COMPARTMENT: CELLULAR_COMPONENT
      DRUG: SIMPLE_CHEMICAL
      ORGAN: ORGAN
  model3:
    etypes:
      CHEMICAL: CHEBI
      ORGANISM: TAXON
  model4:
    etypes:
      CELL_TYPE: CELL_TYPE
      PROTEIN: PROTEIN
  model5:
    etypes:
      PATHWAY: PATHWAY