train:
  corpora:
    dev_size: 0.1  # (float) Proportion. | (int) Number of samples.
    shuffle_seed: 0  # (int) Shuffling applied before the split.
eval:
  disease:
    etype_name: DISEASE
  cell_compartment:
    etype_name: CELLULAR_COMPONENT
  drug:
    etype_name: SIMPLE_CHEMICAL
  organ:
    etype_name: ORGAN
  chemical:
    etype_name: CHEBI
  organism:
    etype_name: TAXON
  cell_type:
    etype_name: CELL_TYPE
  protein:
    etype_name: PROTEIN
  pathway:
    etype_name: PATHWAY
