FROM python:3.6-slim

LABEL maintainer="Stanislav Schmidt <stanislav.schmidt@epfl.ch>"
LABEL version="1.0"
LABEL description="REST API Server for BBSearch"

# ENV HTTP_PROXY='http://bbpproxy.epfl.ch:80/'
# ENV HTTPS_PROXY='http://bbpproxy.epfl.ch:80/'
# ENV http_proxy='http://bbpproxy.epfl.ch:80/'
# ENV https_proxy='http://bbpproxy.epfl.ch:80/'

# Install git, gcc, and g++
RUN apt-get update && apt-get install -y \
    git \
    gcc \
    g++ \
    build-essential \
    vim

# Install requirements manualy, this layer will be cached by docker
COPY requirements.txt /tmp
RUN true \
    && pip install Cython numpy \
    && pip install --no-cache-dir -r /tmp/requirements.txt \
    && rm /tmp/requirements.txt

# Install the app
ADD . /src
WORKDIR /src
RUN pip install .

# Add a user
RUN useradd --create-home serveruser
WORKDIR /home/serveruser
USER serveruser

# Download the NLTK libraries
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"

# Expose a port
EXPOSE 8080
ENV MODELS_PATH="/raid/bbs_data/trained_models"
ENV EMBEDDINGS_PATH="/raid/bbs_data/cord19_v7/embeddings"
ENV DATABASES_PATH="/raid/bbs_data/cord19_v7/databases"

ENTRYPOINT exec search_server \
    --host=0.0.0.0 \
    --port=8080 \
    --models_path $MODELS_PATH \
    --embeddings_path $EMBEDDINGS_PATH \
    --databeses_path $DATABASES_PATH
