FROM python:3.6-slim

# ENV HTTP_PROXY='http://bbpproxy.epfl.ch:80/'
# ENV HTTPS_PROXY='http://bbpproxy.epfl.ch:80/'
# ENV http_proxy='http://bbpproxy.epfl.ch:80/'
# ENV https_proxy='http://bbpproxy.epfl.ch:80/'

# Install git, gcc, and g++
RUN apt-get update && apt-get install -y \
    git \
    gcc g++ \
    build-essential \
    libmysqlclient-dev \
    vim

# Install requirements manualy, this layer will be cached by docker
COPY requirements.txt /tmp
RUN true \
    && pip install Cython numpy \
    && pip install --no-cache-dir -r /tmp/requirements.txt \
    && rm /tmp/requirements.txt \
    && pip install mysqlclient

# Install the app
ADD . /src
WORKDIR /src
RUN pip install .

# Set image version
LABEL maintainer="BBP-EPFL Machine Learning team <bbp-ou-machinelearning@groupes.epfl.ch>"
LABEL description="REST API Server for BBSearch"
LABEL version="$(python -c 'import bbsearch; print(bbsearch.__version__)')"

# Add a user
RUN useradd --create-home serveruser
WORKDIR /home/serveruser
USER serveruser

# Download the NLTK libraries
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"

# Expose a port
EXPOSE 8080

ENV MODELS_PATH="/raid/sync/proj115/bbs_data/trained_models"
ENV EMBEDDINGS_PATH="/raid/sync/proj115/bbs_data/cord19_v35/embeddings/embeddings.h5"
ENV DATABASE_URI="dgx1.bbp.epfl.ch:8853/cord19_v35"
ENV LOG_DIR="/raid/projects/bbs/logs"
ENV LOG_NAME="bbs_search.log"

ENTRYPOINT exec search_server \
    --host=0.0.0.0 \
    --port=8080 \
#    --debug \
    --models_path $MODELS_PATH \
    --embeddings_path $EMBEDDINGS_PATH \
    --database_uri $DATABASE_URI
