stages:
  training:
    foreach:
      - tf_idf
      - count
    do:
      cmd: python train.py --sentences_file=../../annotations/sentence_embedding/cord19_v47_sentences_pre.txt
        --model=${item} --output_dir=../../models/sentence_embedding/${item}
      deps:
        - ../../annotations/sentence_embedding/cord19_v47_sentences_pre.txt
        - Dockerfile
        - train.py
      params:
        - train.${item}
      outs:
        - ../../models/sentence_embedding/${item}
  evaluation:
    foreach:
      - biobert_nli_sts_cord19_v1
      - biobert_nli_sts
      - tf_idf
      - count
      - sbert
      - sbiobert
    do:
      cmd: python eval.py --annotation_files=../../annotations/sentence_embedding/sentence_similarity_cord19.csv
        --model=${item} --output_dir=../../metrics/sentence_embedding
      deps:
      - ../../annotations/sentence_embedding/sentence_similarity_cord19.csv
      - Dockerfile
      - eval.py
      params:
      - eval.${item}
      outs:
      - ../../metrics/sentence_embedding/${item}.csv
      - ../../metrics/sentence_embedding/${item}.png
      metrics:
      - ../../metrics/sentence_embedding/${item}.json:
          cache: false
