name: pypi publishing


on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:

  publish_on_pypi:

    if: startsWith(github.ref, 'refs/tags')

    runs-on: ubuntu-latest

    steps:

      - name: checkout latest commit
        uses: actions/checkout@v2

      - name: setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: create source distribution
        run: |
            python setup.py sdist

      - name: create wheel distribution
        run: |
          python setup.py bdist_wheel

      - name: publish package to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
