name: ci testing


on:
  push:
    branches: master
  pull_request:


jobs:

  run_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [
          3.7,
          3.8,
          3.9,
        ]
        include:
          - python-version: 3.7
          tox-env: py37
          - python-version: 3.8
          tox-env: py38
          - python-version: 3.9
          tox-env: py39

    steps:

      - name: checkout latest commit
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: linting and code style
        run: tox -vv -e lint

      - name: tests and coverage
        run: tox -vv -e ${{ matrix.tox-env }}

      - name: docs
        run: tox -vv -e docs

      - name: check packaging
        run: tox -vv -e check-packaging
